server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**,/orderStates/**
        - id: teamc-delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/** 
        - id: teamc-check
          uri: http://localhost:8083
          predicates:
            - Path=/checks/** 
        - id: teamc-product
          uri: http://localhost:8084
          predicates:
            - Path=/products/** 
        - id: Payment
          uri: http://localhost:8085
          predicates:
            - Path=/payments/** 
        - id: teamc-notify
          uri: http://localhost:8086
          predicates:
            - Path= 
        - id: teamc-assign
          uri: http://localhost:8087
          predicates:
            - Path=             
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://admin06-sk-order:8080
          predicates:
            - Path=/orders/**,/orderStates/**
        - id: Delivery
          uri: http://admin06-sk-delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: Check
          uri: http://admin06-sk-check:8080
          predicates:
            - Path=/checks/** 
        - id: Product
          uri: http://admin06-sk-product:8080
          predicates:
            - Path=/products/** 
        - id: Payment
          uri: http://admin06-sk-payment:8080
          predicates:
            - Path=/payments/** 
        - id: Notify
          uri: http://admin06-sk-notify:8080
          predicates:
            - Path= 
        - id: Assign
          uri: http://admin06-sk-assign:8080
          predicates:
            - Path=/assigns/**       
        - id: User
          uri: http://admin06-sk-user:8080
          predicates:
            - Path=/users/**                 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
